{{- if and .Values.contour.serviceAccount.create .Values.contour.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourServiceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: contour
{{- end }}
{{- if .Values.contour.certgen.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "contour.contourCertGenServiceAccountName" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: contour
{{- end }}
{{- if and .Values.envoy.serviceAccount.create .Values.envoy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy.envoyServiceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: envoy
{{- end }}